/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import clases.Conexion;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author EDUARDO
 */
public class Administrador extends javax.swing.JFrame {

    String usuario, nombreUsuario;
    public static int sesionUsuario;

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();

        usuario = Login.usuario;

        //OPCIONES JFRAME        
        setResizable(false);
        setSize(1280, 720);
        setLocationRelativeTo(null);
        setTitle("Administración - Sesión de " + usuario);

        //JPANELS TRANSPARENTES
        jPanel_Libros.setBackground(new Color(255, 255, 255, 0));
        jPanel_Usuarios.setBackground(new Color(255, 255, 255, 0));
        jPanel3.setBackground(new Color(255, 255, 255, 0));
        jTabbedPane1.setOpaque(false);

        //FONDO IMAGENES
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_wallpaper.getWidth(), jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono_fondo);
        this.repaint();

        ImageIcon addLibro = new ImageIcon("src/images/addbook.png");
        Icon icono_addLibro = new ImageIcon(addLibro.getImage().getScaledInstance(jButton_AgregarLibro.getWidth() - 50, jButton_AgregarLibro.getHeight() - 50, Image.SCALE_DEFAULT));
        jButton_AgregarLibro.setIcon(icono_addLibro);
        ImageIcon delLibro = new ImageIcon("src/images/delbook.png");
        Icon icono_delLibro = new ImageIcon(delLibro.getImage().getScaledInstance(jButton_EliminarLibro.getWidth() - 50, jButton_EliminarLibro.getHeight() - 50, Image.SCALE_DEFAULT));
        jButton_EliminarLibro.setIcon(icono_delLibro);
        jButton_AgregarLibro.setOpaque(false);
        jButton_EliminarLibro.setOpaque(false);

        //CONEXION JDBC
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("SELECT nombre FROM usuarios WHERE username = '" + usuario + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                nombreUsuario = rs.getString("nombre");
                jMenu4.setText(nombreUsuario);

            }
        } catch (SQLException e) {
            System.err.println("Error" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Libros = new javax.swing.JPanel();
        jLabel_NombreLibro = new javax.swing.JLabel();
        jLabel_AutorLibro = new javax.swing.JLabel();
        jLabel_EditorialLibro = new javax.swing.JLabel();
        jLabel_AñoLibro = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton_AgregarLibro = new javax.swing.JButton();
        jButton_EliminarLibro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Usuarios = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_wallpaper = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Libros.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreLibro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_NombreLibro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_NombreLibro.setText("Título:");
        jPanel_Libros.add(jLabel_NombreLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, 20));

        jLabel_AutorLibro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_AutorLibro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AutorLibro.setText("Autor:");
        jPanel_Libros.add(jLabel_AutorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, -1));

        jLabel_EditorialLibro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_EditorialLibro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_EditorialLibro.setText("Editorial:");
        jPanel_Libros.add(jLabel_EditorialLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        jLabel_AñoLibro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_AñoLibro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_AñoLibro.setText("Año:");
        jPanel_Libros.add(jLabel_AñoLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel_Libros.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 510, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel_Libros.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 510, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel_Libros.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 510, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel_Libros.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 510, -1));

        jButton_AgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarLibroActionPerformed(evt);
            }
        });
        jPanel_Libros.add(jButton_AgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 100, 100));

        jButton_EliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarLibroActionPerformed(evt);
            }
        });
        jPanel_Libros.add(jButton_EliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 100, 100));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Modificar Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel_Libros.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 620, 580));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Agregar Libro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel_Libros.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 580));

        jTabbedPane1.addTab("Libros", jPanel_Libros);

        jPanel_Usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("Usuarios", jPanel_Usuarios);
        jTabbedPane1.addTab("Biblioteca", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 690));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setEnabled(false);
        jMenu3.setHideActionText(true);
        jMenu3.setPreferredSize(new java.awt.Dimension(1000, 24));
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");
        jMenu4.setPreferredSize(new java.awt.Dimension(180, 24));
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AgregarLibroActionPerformed

    private void jButton_EliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_EliminarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AgregarLibro;
    private javax.swing.JButton jButton_EliminarLibro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_AutorLibro;
    private javax.swing.JLabel jLabel_AñoLibro;
    private javax.swing.JLabel jLabel_EditorialLibro;
    private javax.swing.JLabel jLabel_NombreLibro;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Libros;
    private javax.swing.JPanel jPanel_Usuarios;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
