/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import clases.Conexion;

/**
 *
 * @author diego, eduardo
 */
public class Login extends javax.swing.JFrame {

    public static String usuario = "";
    String contrasena = "";

    /**
     * Creates new form Login
     */
    public Login() {

        initComponents();
        setResizable(false);
        setSize(400, 550);
        setLocationRelativeTo(null);
        setTitle("Acceso Biblioteca");
        jLabel_logo.requestFocus();

        //CAMBIAR FONDO
        ImageIcon fondo = new ImageIcon("src/images/fondo.jpg");
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jLabel_wallpaper.getWidth(), jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono_fondo);
        this.repaint();

        //CAMBIAR LOGO LOGIN
        ImageIcon logo = new ImageIcon("src/images/logo.png");
        Icon icono_logo = new ImageIcon(logo.getImage().getScaledInstance(jLabel_logo.getWidth(), jLabel_logo.getHeight(), Image.SCALE_DEFAULT));
        jLabel_logo.setIcon(icono_logo);

        //CAMBIAR OJO PASS
        ImageIcon ver = new ImageIcon("src/images/eye.png");
        Icon icono_ver = new ImageIcon(ver.getImage().getScaledInstance(jLabel_verPass.getWidth(), jLabel_verPass.getHeight(), Image.SCALE_DEFAULT));
        jLabel_verPass.setIcon(icono_ver);

        //CAMBIAR ICONO VENTANA
        ImageIcon img = new ImageIcon("src/images/logo.png"); //icono.png
        setIconImage(img.getImage());

        //TECLA ENTER ACCIONA AL BOTON POR DEFECTO       
        SwingUtilities.getRootPane(jButton_Acceder).setDefaultButton(jButton_Acceder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TextoLibreria_lechosa = new javax.swing.JLabel();
        jLabel_verPass = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contrasena = new javax.swing.JPasswordField();
        jButton_Acceder = new javax.swing.JButton();
        jLabel_logo = new javax.swing.JLabel();
        jLabel_bievenida = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TextoLibreria_lechosa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TextoLibreria_lechosa.setText("Libreria Lechosa S.A de C.V ©.®.");
        getContentPane().add(jLabel_TextoLibreria_lechosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 400, -1));

        jLabel_verPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_verPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_verPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_verPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_verPassMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_verPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 30, 30));

        tf_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_usuario.setForeground(java.awt.Color.lightGray);
        tf_usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_usuario.setText("USUARIO");
        tf_usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tf_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_usuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_usuarioFocusLost(evt);
            }
        });
        getContentPane().add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 180, -1));

        tf_contrasena.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf_contrasena.setForeground(java.awt.Color.lightGray);
        tf_contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_contrasena.setText("CONTRASEÑA");
        tf_contrasena.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tf_contrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_contrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_contrasenaFocusLost(evt);
            }
        });
        getContentPane().add(tf_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 180, -1));

        jButton_Acceder.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Acceder.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_Acceder.setText("ACCEDER");
        jButton_Acceder.setBorder(null);
        jButton_Acceder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AccederActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Acceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 180, 30));
        getContentPane().add(jLabel_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, 200));

        jLabel_bievenida.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel_bievenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_bievenida.setText("BIENVENID@");
        getContentPane().add(jLabel_bievenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 220, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AccederActionPerformed

        usuario = tf_usuario.getText().trim();
        contrasena = tf_contrasena.getText().trim();

        if (!usuario.equals("") && !usuario.equals("USUARIO") || !contrasena.equals("") && !contrasena.equals("CONTRASEÑA")) {
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement("select permiso, estatus from usuarios where username='" + usuario + "' and contrasena='" + contrasena + "'");
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    int permiso = rs.getInt("permiso");
                    boolean estatus = rs.getBoolean("estatus");
                    if (estatus && permiso == 3) {
                        dispose();
                        new Administrador().setVisible(true);
                    } else if (estatus && permiso == 2) {
                        dispose();
                        new Bibliotecario().setVisible(true); 
                    } else if (estatus && permiso == 1) {
                        dispose();
                        new Usuario().setVisible(true); 
                    }
                    if (!estatus) {
                        JOptionPane.showMessageDialog(rootPane, "USUARIO INACTIVO", "ACCESO DENEGADO", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Credenciales errónaes, intenta de nuevo.");
                    tf_usuario.setText("");
                    tf_contrasena.setText("");
                }
            } catch (SQLException e) { //SQLExceptiondiwgo
                System.err.println("Error " + e);
                JOptionPane.showMessageDialog(null, "Error al iniciar sesión, contacte al administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
        }

    }//GEN-LAST:event_jButton_AccederActionPerformed

    private void jLabel_verPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_verPassMouseEntered
        tf_contrasena.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel_verPassMouseEntered

    private void jLabel_verPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_verPassMouseExited
        tf_contrasena.setEchoChar('*');
    }//GEN-LAST:event_jLabel_verPassMouseExited

    private void tf_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usuarioFocusGained
        if (tf_usuario.getText().equals("USUARIO")) {
            tf_usuario.setText("");
            tf_usuario.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_usuarioFocusGained

    private void tf_usuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usuarioFocusLost
        if (tf_usuario.getText().equals("")) {
            tf_usuario.setText("USUARIO");
            tf_usuario.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_tf_usuarioFocusLost

    private void tf_contrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_contrasenaFocusGained
        if (tf_contrasena.getText().equals("CONTRASEÑA")) {
            tf_contrasena.setText("");
            tf_contrasena.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tf_contrasenaFocusGained

    private void tf_contrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_contrasenaFocusLost
        if (tf_contrasena.getText().equals("")) {
            tf_contrasena.setText("CONTRASEÑA");
            tf_contrasena.setForeground(Color.LIGHT_GRAY);
        }
    }//GEN-LAST:event_tf_contrasenaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Acceder;
    private javax.swing.JLabel jLabel_TextoLibreria_lechosa;
    private javax.swing.JLabel jLabel_bievenida;
    private javax.swing.JLabel jLabel_logo;
    private javax.swing.JLabel jLabel_verPass;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JPasswordField tf_contrasena;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration//GEN-END:variables
}
